// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: utlxe/v1/utlxe.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorClass int32

const (
	ErrorClass_ERROR_CLASS_UNSPECIFIED ErrorClass = 0
	ErrorClass_PERMANENT               ErrorClass = 1 // Missing field, type coercion failure — do not retry
	ErrorClass_TRANSIENT               ErrorClass = 2 // Expression error (e.g., division by zero) — retryable
)

// Enum value maps for ErrorClass.
var (
	ErrorClass_name = map[int32]string{
		0: "ERROR_CLASS_UNSPECIFIED",
		1: "PERMANENT",
		2: "TRANSIENT",
	}
	ErrorClass_value = map[string]int32{
		"ERROR_CLASS_UNSPECIFIED": 0,
		"PERMANENT":               1,
		"TRANSIENT":               2,
	}
)

func (x ErrorClass) Enum() *ErrorClass {
	p := new(ErrorClass)
	*p = x
	return p
}

func (x ErrorClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorClass) Descriptor() protoreflect.EnumDescriptor {
	return file_utlxe_v1_utlxe_proto_enumTypes[0].Descriptor()
}

func (ErrorClass) Type() protoreflect.EnumType {
	return &file_utlxe_v1_utlxe_proto_enumTypes[0]
}

func (x ErrorClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorClass.Descriptor instead.
func (ErrorClass) EnumDescriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{0}
}

type ErrorPhase int32

const (
	ErrorPhase_ERROR_PHASE_UNSPECIFIED ErrorPhase = 0
	ErrorPhase_PRE_VALIDATION          ErrorPhase = 1 // Input schema validation failed
	ErrorPhase_TRANSFORMATION          ErrorPhase = 2 // utl-x execution failed
	ErrorPhase_POST_VALIDATION         ErrorPhase = 3 // Output schema validation failed
	ErrorPhase_INTERNAL                ErrorPhase = 4 // UTLXe engine error (not payload-related)
)

// Enum value maps for ErrorPhase.
var (
	ErrorPhase_name = map[int32]string{
		0: "ERROR_PHASE_UNSPECIFIED",
		1: "PRE_VALIDATION",
		2: "TRANSFORMATION",
		3: "POST_VALIDATION",
		4: "INTERNAL",
	}
	ErrorPhase_value = map[string]int32{
		"ERROR_PHASE_UNSPECIFIED": 0,
		"PRE_VALIDATION":          1,
		"TRANSFORMATION":          2,
		"POST_VALIDATION":         3,
		"INTERNAL":                4,
	}
)

func (x ErrorPhase) Enum() *ErrorPhase {
	p := new(ErrorPhase)
	*p = x
	return p
}

func (x ErrorPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_utlxe_v1_utlxe_proto_enumTypes[1].Descriptor()
}

func (ErrorPhase) Type() protoreflect.EnumType {
	return &file_utlxe_v1_utlxe_proto_enumTypes[1]
}

func (x ErrorPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorPhase.Descriptor instead.
func (ErrorPhase) EnumDescriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{1}
}

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	// Requests (wrapper → UTLXe)
	MessageType_LOAD_TRANSFORMATION_REQUEST   MessageType = 1
	MessageType_EXECUTE_REQUEST               MessageType = 2
	MessageType_EXECUTE_BATCH_REQUEST         MessageType = 3
	MessageType_UNLOAD_TRANSFORMATION_REQUEST MessageType = 4
	MessageType_HEALTH_REQUEST                MessageType = 5
	MessageType_EXECUTE_PIPELINE_REQUEST      MessageType = 6
	// Responses (UTLXe → wrapper)
	MessageType_LOAD_TRANSFORMATION_RESPONSE   MessageType = 11
	MessageType_EXECUTE_RESPONSE               MessageType = 12
	MessageType_EXECUTE_BATCH_RESPONSE         MessageType = 13
	MessageType_UNLOAD_TRANSFORMATION_RESPONSE MessageType = 14
	MessageType_HEALTH_RESPONSE                MessageType = 15
	MessageType_EXECUTE_PIPELINE_RESPONSE      MessageType = 16
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MESSAGE_TYPE_UNSPECIFIED",
		1:  "LOAD_TRANSFORMATION_REQUEST",
		2:  "EXECUTE_REQUEST",
		3:  "EXECUTE_BATCH_REQUEST",
		4:  "UNLOAD_TRANSFORMATION_REQUEST",
		5:  "HEALTH_REQUEST",
		6:  "EXECUTE_PIPELINE_REQUEST",
		11: "LOAD_TRANSFORMATION_RESPONSE",
		12: "EXECUTE_RESPONSE",
		13: "EXECUTE_BATCH_RESPONSE",
		14: "UNLOAD_TRANSFORMATION_RESPONSE",
		15: "HEALTH_RESPONSE",
		16: "EXECUTE_PIPELINE_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":       0,
		"LOAD_TRANSFORMATION_REQUEST":    1,
		"EXECUTE_REQUEST":                2,
		"EXECUTE_BATCH_REQUEST":          3,
		"UNLOAD_TRANSFORMATION_REQUEST":  4,
		"HEALTH_REQUEST":                 5,
		"EXECUTE_PIPELINE_REQUEST":       6,
		"LOAD_TRANSFORMATION_RESPONSE":   11,
		"EXECUTE_RESPONSE":               12,
		"EXECUTE_BATCH_RESPONSE":         13,
		"UNLOAD_TRANSFORMATION_RESPONSE": 14,
		"HEALTH_RESPONSE":                15,
		"EXECUTE_PIPELINE_RESPONSE":      16,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_utlxe_v1_utlxe_proto_enumTypes[2].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_utlxe_v1_utlxe_proto_enumTypes[2]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{2}
}

type LoadTransformationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransformationId string                 `protobuf:"bytes,1,opt,name=transformation_id,json=transformationId,proto3" json:"transformation_id,omitempty"`                               // Unique ID (e.g., connection ID from pipeline descriptor)
	UtlxSource       string                 `protobuf:"bytes,2,opt,name=utlx_source,json=utlxSource,proto3" json:"utlx_source,omitempty"`                                                 // The .utlx mapping definition source code
	Strategy         string                 `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`                                                                       // "TEMPLATE", "COPY", "COMPILED", "AUTO" (default: "AUTO")
	ValidationPolicy string                 `protobuf:"bytes,4,opt,name=validation_policy,json=validationPolicy,proto3" json:"validation_policy,omitempty"`                               // "STRICT", "WARN", "SKIP" (default: "SKIP")
	MaxConcurrent    int32                  `protobuf:"varint,5,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`                                       // Per-transformation concurrency limit (0 = use engine default)
	Config           map[string]string      `protobuf:"bytes,6,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional configuration (validation settings, format hints, etc.)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoadTransformationRequest) Reset() {
	*x = LoadTransformationRequest{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTransformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTransformationRequest) ProtoMessage() {}

func (x *LoadTransformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTransformationRequest.ProtoReflect.Descriptor instead.
func (*LoadTransformationRequest) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{0}
}

func (x *LoadTransformationRequest) GetTransformationId() string {
	if x != nil {
		return x.TransformationId
	}
	return ""
}

func (x *LoadTransformationRequest) GetUtlxSource() string {
	if x != nil {
		return x.UtlxSource
	}
	return ""
}

func (x *LoadTransformationRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *LoadTransformationRequest) GetValidationPolicy() string {
	if x != nil {
		return x.ValidationPolicy
	}
	return ""
}

func (x *LoadTransformationRequest) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *LoadTransformationRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type LoadTransformationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`       // Non-empty if success=false
	Warnings      []*ValidationError     `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"` // Type-check warnings (non-fatal)
	Metrics       *LoadMetrics           `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`   // Compilation timing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTransformationResponse) Reset() {
	*x = LoadTransformationResponse{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTransformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTransformationResponse) ProtoMessage() {}

func (x *LoadTransformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTransformationResponse.ProtoReflect.Descriptor instead.
func (*LoadTransformationResponse) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{1}
}

func (x *LoadTransformationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadTransformationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LoadTransformationResponse) GetWarnings() []*ValidationError {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *LoadTransformationResponse) GetMetrics() *LoadMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type LoadMetrics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ParseDurationUs     int64                  `protobuf:"varint,1,opt,name=parse_duration_us,json=parseDurationUs,proto3" json:"parse_duration_us,omitempty"`             // Microseconds for lexer + parser
	TypecheckDurationUs int64                  `protobuf:"varint,2,opt,name=typecheck_duration_us,json=typecheckDurationUs,proto3" json:"typecheck_duration_us,omitempty"` // Microseconds for type checker
	TotalDurationUs     int64                  `protobuf:"varint,3,opt,name=total_duration_us,json=totalDurationUs,proto3" json:"total_duration_us,omitempty"`             // Total init time
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoadMetrics) Reset() {
	*x = LoadMetrics{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMetrics) ProtoMessage() {}

func (x *LoadMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMetrics.ProtoReflect.Descriptor instead.
func (*LoadMetrics) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{2}
}

func (x *LoadMetrics) GetParseDurationUs() int64 {
	if x != nil {
		return x.ParseDurationUs
	}
	return 0
}

func (x *LoadMetrics) GetTypecheckDurationUs() int64 {
	if x != nil {
		return x.TypecheckDurationUs
	}
	return 0
}

func (x *LoadMetrics) GetTotalDurationUs() int64 {
	if x != nil {
		return x.TotalDurationUs
	}
	return 0
}

type ExecuteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransformationId string                 `protobuf:"bytes,1,opt,name=transformation_id,json=transformationId,proto3" json:"transformation_id,omitempty"`                                                            // Which pre-loaded transformation to execute
	Payload          []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                                                                                                      // The current_payload from MPPM envelope
	ContentType      string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`                                                                           // "application/json", "application/xml", "text/csv", etc.
	NamedInputs      map[string][]byte      `protobuf:"bytes,4,rep,name=named_inputs,json=namedInputs,proto3" json:"named_inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // For N-input mappings: named payloads from step window
	CorrelationId    string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`                                                                     // For tracing/debugging and multiplexed response matching
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRequest) GetTransformationId() string {
	if x != nil {
		return x.TransformationId
	}
	return ""
}

func (x *ExecuteRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExecuteRequest) GetNamedInputs() map[string][]byte {
	if x != nil {
		return x.NamedInputs
	}
	return nil
}

func (x *ExecuteRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ExecuteResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output            []byte                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`                                                     // Transformed payload
	OutputContentType string                 `protobuf:"bytes,3,opt,name=output_content_type,json=outputContentType,proto3" json:"output_content_type,omitempty"`    // Output format
	Error             string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                                                       // Non-empty if success=false
	ErrorClass        ErrorClass             `protobuf:"varint,5,opt,name=error_class,json=errorClass,proto3,enum=utlxe.v1.ErrorClass" json:"error_class,omitempty"` // PERMANENT or TRANSIENT
	ValidationErrors  []*ValidationError     `protobuf:"bytes,6,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	Metrics           *ExecuteMetrics        `protobuf:"bytes,7,opt,name=metrics,proto3" json:"metrics,omitempty"`
	ErrorPhase        ErrorPhase             `protobuf:"varint,8,opt,name=error_phase,json=errorPhase,proto3,enum=utlxe.v1.ErrorPhase" json:"error_phase,omitempty"` // WHERE the error occurred
	CorrelationId     string                 `protobuf:"bytes,9,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`                  // Echoed from request (for multiplexed matching)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecuteResponse) GetOutputContentType() string {
	if x != nil {
		return x.OutputContentType
	}
	return ""
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetErrorClass() ErrorClass {
	if x != nil {
		return x.ErrorClass
	}
	return ErrorClass_ERROR_CLASS_UNSPECIFIED
}

func (x *ExecuteResponse) GetValidationErrors() []*ValidationError {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

func (x *ExecuteResponse) GetMetrics() *ExecuteMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ExecuteResponse) GetErrorPhase() ErrorPhase {
	if x != nil {
		return x.ErrorPhase
	}
	return ErrorPhase_ERROR_PHASE_UNSPECIFIED
}

func (x *ExecuteResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`         // JSONPath or XPath to the problematic field
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"` // "ERROR", "WARNING"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{5}
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ValidationError) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type ExecuteMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExecuteDurationUs int64                  `protobuf:"varint,1,opt,name=execute_duration_us,json=executeDurationUs,proto3" json:"execute_duration_us,omitempty"` // Microseconds for this execution
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecuteMetrics) Reset() {
	*x = ExecuteMetrics{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteMetrics) ProtoMessage() {}

func (x *ExecuteMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteMetrics.ProtoReflect.Descriptor instead.
func (*ExecuteMetrics) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteMetrics) GetExecuteDurationUs() int64 {
	if x != nil {
		return x.ExecuteDurationUs
	}
	return 0
}

type ExecuteBatchRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransformationId string                 `protobuf:"bytes,1,opt,name=transformation_id,json=transformationId,proto3" json:"transformation_id,omitempty"`
	Items            []*BatchItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecuteBatchRequest) Reset() {
	*x = ExecuteBatchRequest{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchRequest) ProtoMessage() {}

func (x *ExecuteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchRequest.ProtoReflect.Descriptor instead.
func (*ExecuteBatchRequest) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteBatchRequest) GetTransformationId() string {
	if x != nil {
		return x.TransformationId
	}
	return ""
}

func (x *ExecuteBatchRequest) GetItems() []*BatchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	NamedInputs   map[string][]byte      `protobuf:"bytes,3,rep,name=named_inputs,json=namedInputs,proto3" json:"named_inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchItem) Reset() {
	*x = BatchItem{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchItem) ProtoMessage() {}

func (x *BatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchItem.ProtoReflect.Descriptor instead.
func (*BatchItem) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{8}
}

func (x *BatchItem) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BatchItem) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *BatchItem) GetNamedInputs() map[string][]byte {
	if x != nil {
		return x.NamedInputs
	}
	return nil
}

func (x *BatchItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ExecuteBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ExecuteResponse     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBatchResponse) Reset() {
	*x = ExecuteBatchResponse{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchResponse) ProtoMessage() {}

func (x *ExecuteBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchResponse.ProtoReflect.Descriptor instead.
func (*ExecuteBatchResponse) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteBatchResponse) GetResults() []*ExecuteResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type ExecutePipelineRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransformationIds []string               `protobuf:"bytes,1,rep,name=transformation_ids,json=transformationIds,proto3" json:"transformation_ids,omitempty"` // Ordered list: output of [0] feeds input of [1], etc.
	Payload           []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                                              // Initial input payload
	ContentType       string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	CorrelationId     string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecutePipelineRequest) Reset() {
	*x = ExecutePipelineRequest{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePipelineRequest) ProtoMessage() {}

func (x *ExecutePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePipelineRequest.ProtoReflect.Descriptor instead.
func (*ExecutePipelineRequest) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{10}
}

func (x *ExecutePipelineRequest) GetTransformationIds() []string {
	if x != nil {
		return x.TransformationIds
	}
	return nil
}

func (x *ExecutePipelineRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecutePipelineRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExecutePipelineRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ExecutePipelineResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output            []byte                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // Final output (from last transformation in chain)
	OutputContentType string                 `protobuf:"bytes,3,opt,name=output_content_type,json=outputContentType,proto3" json:"output_content_type,omitempty"`
	Error             string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ErrorClass        ErrorClass             `protobuf:"varint,5,opt,name=error_class,json=errorClass,proto3,enum=utlxe.v1.ErrorClass" json:"error_class,omitempty"`
	ErrorPhase        ErrorPhase             `protobuf:"varint,6,opt,name=error_phase,json=errorPhase,proto3,enum=utlxe.v1.ErrorPhase" json:"error_phase,omitempty"`
	ValidationErrors  []*ValidationError     `protobuf:"bytes,7,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	CorrelationId     string                 `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	StagesCompleted   int32                  `protobuf:"varint,9,opt,name=stages_completed,json=stagesCompleted,proto3" json:"stages_completed,omitempty"`    // How many transforms completed before error (or total)
	TotalDurationUs   int64                  `protobuf:"varint,10,opt,name=total_duration_us,json=totalDurationUs,proto3" json:"total_duration_us,omitempty"` // Wall clock for entire pipeline
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecutePipelineResponse) Reset() {
	*x = ExecutePipelineResponse{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePipelineResponse) ProtoMessage() {}

func (x *ExecutePipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePipelineResponse.ProtoReflect.Descriptor instead.
func (*ExecutePipelineResponse) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{11}
}

func (x *ExecutePipelineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecutePipelineResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecutePipelineResponse) GetOutputContentType() string {
	if x != nil {
		return x.OutputContentType
	}
	return ""
}

func (x *ExecutePipelineResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecutePipelineResponse) GetErrorClass() ErrorClass {
	if x != nil {
		return x.ErrorClass
	}
	return ErrorClass_ERROR_CLASS_UNSPECIFIED
}

func (x *ExecutePipelineResponse) GetErrorPhase() ErrorPhase {
	if x != nil {
		return x.ErrorPhase
	}
	return ErrorPhase_ERROR_PHASE_UNSPECIFIED
}

func (x *ExecutePipelineResponse) GetValidationErrors() []*ValidationError {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

func (x *ExecutePipelineResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ExecutePipelineResponse) GetStagesCompleted() int32 {
	if x != nil {
		return x.StagesCompleted
	}
	return 0
}

func (x *ExecutePipelineResponse) GetTotalDurationUs() int64 {
	if x != nil {
		return x.TotalDurationUs
	}
	return 0
}

type UnloadTransformationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransformationId string                 `protobuf:"bytes,1,opt,name=transformation_id,json=transformationId,proto3" json:"transformation_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UnloadTransformationRequest) Reset() {
	*x = UnloadTransformationRequest{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadTransformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadTransformationRequest) ProtoMessage() {}

func (x *UnloadTransformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadTransformationRequest.ProtoReflect.Descriptor instead.
func (*UnloadTransformationRequest) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{12}
}

func (x *UnloadTransformationRequest) GetTransformationId() string {
	if x != nil {
		return x.TransformationId
	}
	return ""
}

type UnloadTransformationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadTransformationResponse) Reset() {
	*x = UnloadTransformationResponse{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadTransformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadTransformationResponse) ProtoMessage() {}

func (x *UnloadTransformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadTransformationResponse.ProtoReflect.Descriptor instead.
func (*UnloadTransformationResponse) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{13}
}

func (x *UnloadTransformationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{14}
}

type HealthResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	State                 string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // "READY", "RUNNING", "DRAINING", etc.
	UptimeMs              int64                  `protobuf:"varint,2,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	LoadedTransformations int32                  `protobuf:"varint,3,opt,name=loaded_transformations,json=loadedTransformations,proto3" json:"loaded_transformations,omitempty"`
	TotalExecutions       int64                  `protobuf:"varint,4,opt,name=total_executions,json=totalExecutions,proto3" json:"total_executions,omitempty"`
	TotalErrors           int64                  `protobuf:"varint,5,opt,name=total_errors,json=totalErrors,proto3" json:"total_errors,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{15}
}

func (x *HealthResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *HealthResponse) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

func (x *HealthResponse) GetLoadedTransformations() int32 {
	if x != nil {
		return x.LoadedTransformations
	}
	return 0
}

func (x *HealthResponse) GetTotalExecutions() int64 {
	if x != nil {
		return x.TotalExecutions
	}
	return 0
}

func (x *HealthResponse) GetTotalErrors() int64 {
	if x != nil {
		return x.TotalErrors
	}
	return 0
}

type StdioEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=utlxe.v1.MessageType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // Serialised inner message (one of the types above)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdioEnvelope) Reset() {
	*x = StdioEnvelope{}
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdioEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdioEnvelope) ProtoMessage() {}

func (x *StdioEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_utlxe_v1_utlxe_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdioEnvelope.ProtoReflect.Descriptor instead.
func (*StdioEnvelope) Descriptor() ([]byte, []int) {
	return file_utlxe_v1_utlxe_proto_rawDescGZIP(), []int{16}
}

func (x *StdioEnvelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *StdioEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_utlxe_v1_utlxe_proto protoreflect.FileDescriptor

const file_utlxe_v1_utlxe_proto_rawDesc = "" +
	"\n" +
	"\x14utlxe/v1/utlxe.proto\x12\butlxe.v1\"\xdd\x02\n" +
	"\x19LoadTransformationRequest\x12+\n" +
	"\x11transformation_id\x18\x01 \x01(\tR\x10transformationId\x12\x1f\n" +
	"\vutlx_source\x18\x02 \x01(\tR\n" +
	"utlxSource\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy\x12+\n" +
	"\x11validation_policy\x18\x04 \x01(\tR\x10validationPolicy\x12%\n" +
	"\x0emax_concurrent\x18\x05 \x01(\x05R\rmaxConcurrent\x12G\n" +
	"\x06config\x18\x06 \x03(\v2/.utlxe.v1.LoadTransformationRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\x1aLoadTransformationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x125\n" +
	"\bwarnings\x18\x03 \x03(\v2\x19.utlxe.v1.ValidationErrorR\bwarnings\x12/\n" +
	"\ametrics\x18\x04 \x01(\v2\x15.utlxe.v1.LoadMetricsR\ametrics\"\x99\x01\n" +
	"\vLoadMetrics\x12*\n" +
	"\x11parse_duration_us\x18\x01 \x01(\x03R\x0fparseDurationUs\x122\n" +
	"\x15typecheck_duration_us\x18\x02 \x01(\x03R\x13typecheckDurationUs\x12*\n" +
	"\x11total_duration_us\x18\x03 \x01(\x03R\x0ftotalDurationUs\"\xaf\x02\n" +
	"\x0eExecuteRequest\x12+\n" +
	"\x11transformation_id\x18\x01 \x01(\tR\x10transformationId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12L\n" +
	"\fnamed_inputs\x18\x04 \x03(\v2).utlxe.v1.ExecuteRequest.NamedInputsEntryR\vnamedInputs\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x1a>\n" +
	"\x10NamedInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x9a\x03\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\x12.\n" +
	"\x13output_content_type\x18\x03 \x01(\tR\x11outputContentType\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x125\n" +
	"\verror_class\x18\x05 \x01(\x0e2\x14.utlxe.v1.ErrorClassR\n" +
	"errorClass\x12F\n" +
	"\x11validation_errors\x18\x06 \x03(\v2\x19.utlxe.v1.ValidationErrorR\x10validationErrors\x122\n" +
	"\ametrics\x18\a \x01(\v2\x18.utlxe.v1.ExecuteMetricsR\ametrics\x125\n" +
	"\verror_phase\x18\b \x01(\x0e2\x14.utlxe.v1.ErrorPhaseR\n" +
	"errorPhase\x12%\n" +
	"\x0ecorrelation_id\x18\t \x01(\tR\rcorrelationId\"[\n" +
	"\x0fValidationError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\"@\n" +
	"\x0eExecuteMetrics\x12.\n" +
	"\x13execute_duration_us\x18\x01 \x01(\x03R\x11executeDurationUs\"m\n" +
	"\x13ExecuteBatchRequest\x12+\n" +
	"\x11transformation_id\x18\x01 \x01(\tR\x10transformationId\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.utlxe.v1.BatchItemR\x05items\"\xf8\x01\n" +
	"\tBatchItem\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12G\n" +
	"\fnamed_inputs\x18\x03 \x03(\v2$.utlxe.v1.BatchItem.NamedInputsEntryR\vnamedInputs\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x1a>\n" +
	"\x10NamedInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"K\n" +
	"\x14ExecuteBatchResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.utlxe.v1.ExecuteResponseR\aresults\"\xab\x01\n" +
	"\x16ExecutePipelineRequest\x12-\n" +
	"\x12transformation_ids\x18\x01 \x03(\tR\x11transformationIds\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\"\xc5\x03\n" +
	"\x17ExecutePipelineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\x12.\n" +
	"\x13output_content_type\x18\x03 \x01(\tR\x11outputContentType\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x125\n" +
	"\verror_class\x18\x05 \x01(\x0e2\x14.utlxe.v1.ErrorClassR\n" +
	"errorClass\x125\n" +
	"\verror_phase\x18\x06 \x01(\x0e2\x14.utlxe.v1.ErrorPhaseR\n" +
	"errorPhase\x12F\n" +
	"\x11validation_errors\x18\a \x03(\v2\x19.utlxe.v1.ValidationErrorR\x10validationErrors\x12%\n" +
	"\x0ecorrelation_id\x18\b \x01(\tR\rcorrelationId\x12)\n" +
	"\x10stages_completed\x18\t \x01(\x05R\x0fstagesCompleted\x12*\n" +
	"\x11total_duration_us\x18\n" +
	" \x01(\x03R\x0ftotalDurationUs\"J\n" +
	"\x1bUnloadTransformationRequest\x12+\n" +
	"\x11transformation_id\x18\x01 \x01(\tR\x10transformationId\"8\n" +
	"\x1cUnloadTransformationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x0f\n" +
	"\rHealthRequest\"\xc8\x01\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1b\n" +
	"\tuptime_ms\x18\x02 \x01(\x03R\buptimeMs\x125\n" +
	"\x16loaded_transformations\x18\x03 \x01(\x05R\x15loadedTransformations\x12)\n" +
	"\x10total_executions\x18\x04 \x01(\x03R\x0ftotalExecutions\x12!\n" +
	"\ftotal_errors\x18\x05 \x01(\x03R\vtotalErrors\"T\n" +
	"\rStdioEnvelope\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.utlxe.v1.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload*G\n" +
	"\n" +
	"ErrorClass\x12\x1b\n" +
	"\x17ERROR_CLASS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tPERMANENT\x10\x01\x12\r\n" +
	"\tTRANSIENT\x10\x02*t\n" +
	"\n" +
	"ErrorPhase\x12\x1b\n" +
	"\x17ERROR_PHASE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePRE_VALIDATION\x10\x01\x12\x12\n" +
	"\x0eTRANSFORMATION\x10\x02\x12\x13\n" +
	"\x0fPOST_VALIDATION\x10\x03\x12\f\n" +
	"\bINTERNAL\x10\x04*\xfd\x02\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bLOAD_TRANSFORMATION_REQUEST\x10\x01\x12\x13\n" +
	"\x0fEXECUTE_REQUEST\x10\x02\x12\x19\n" +
	"\x15EXECUTE_BATCH_REQUEST\x10\x03\x12!\n" +
	"\x1dUNLOAD_TRANSFORMATION_REQUEST\x10\x04\x12\x12\n" +
	"\x0eHEALTH_REQUEST\x10\x05\x12\x1c\n" +
	"\x18EXECUTE_PIPELINE_REQUEST\x10\x06\x12 \n" +
	"\x1cLOAD_TRANSFORMATION_RESPONSE\x10\v\x12\x14\n" +
	"\x10EXECUTE_RESPONSE\x10\f\x12\x1a\n" +
	"\x16EXECUTE_BATCH_RESPONSE\x10\r\x12\"\n" +
	"\x1eUNLOAD_TRANSFORMATION_RESPONSE\x10\x0e\x12\x13\n" +
	"\x0fHEALTH_RESPONSE\x10\x0f\x12\x1d\n" +
	"\x19EXECUTE_PIPELINE_RESPONSE\x10\x102\xfa\x03\n" +
	"\fUtlxeService\x12_\n" +
	"\x12LoadTransformation\x12#.utlxe.v1.LoadTransformationRequest\x1a$.utlxe.v1.LoadTransformationResponse\x12>\n" +
	"\aExecute\x12\x18.utlxe.v1.ExecuteRequest\x1a\x19.utlxe.v1.ExecuteResponse\x12M\n" +
	"\fExecuteBatch\x12\x1d.utlxe.v1.ExecuteBatchRequest\x1a\x1e.utlxe.v1.ExecuteBatchResponse\x12e\n" +
	"\x14UnloadTransformation\x12%.utlxe.v1.UnloadTransformationRequest\x1a&.utlxe.v1.UnloadTransformationResponse\x12V\n" +
	"\x0fExecutePipeline\x12 .utlxe.v1.ExecutePipelineRequest\x1a!.utlxe.v1.ExecutePipelineResponse\x12;\n" +
	"\x06Health\x12\x17.utlxe.v1.HealthRequest\x1a\x18.utlxe.v1.HealthResponseB,\n" +
	"\x1corg.apache.utlx.engine.protoB\n" +
	"UtlxeProtoP\x01b\x06proto3"

var (
	file_utlxe_v1_utlxe_proto_rawDescOnce sync.Once
	file_utlxe_v1_utlxe_proto_rawDescData []byte
)

func file_utlxe_v1_utlxe_proto_rawDescGZIP() []byte {
	file_utlxe_v1_utlxe_proto_rawDescOnce.Do(func() {
		file_utlxe_v1_utlxe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utlxe_v1_utlxe_proto_rawDesc), len(file_utlxe_v1_utlxe_proto_rawDesc)))
	})
	return file_utlxe_v1_utlxe_proto_rawDescData
}

var file_utlxe_v1_utlxe_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_utlxe_v1_utlxe_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_utlxe_v1_utlxe_proto_goTypes = []any{
	(ErrorClass)(0),                      // 0: utlxe.v1.ErrorClass
	(ErrorPhase)(0),                      // 1: utlxe.v1.ErrorPhase
	(MessageType)(0),                     // 2: utlxe.v1.MessageType
	(*LoadTransformationRequest)(nil),    // 3: utlxe.v1.LoadTransformationRequest
	(*LoadTransformationResponse)(nil),   // 4: utlxe.v1.LoadTransformationResponse
	(*LoadMetrics)(nil),                  // 5: utlxe.v1.LoadMetrics
	(*ExecuteRequest)(nil),               // 6: utlxe.v1.ExecuteRequest
	(*ExecuteResponse)(nil),              // 7: utlxe.v1.ExecuteResponse
	(*ValidationError)(nil),              // 8: utlxe.v1.ValidationError
	(*ExecuteMetrics)(nil),               // 9: utlxe.v1.ExecuteMetrics
	(*ExecuteBatchRequest)(nil),          // 10: utlxe.v1.ExecuteBatchRequest
	(*BatchItem)(nil),                    // 11: utlxe.v1.BatchItem
	(*ExecuteBatchResponse)(nil),         // 12: utlxe.v1.ExecuteBatchResponse
	(*ExecutePipelineRequest)(nil),       // 13: utlxe.v1.ExecutePipelineRequest
	(*ExecutePipelineResponse)(nil),      // 14: utlxe.v1.ExecutePipelineResponse
	(*UnloadTransformationRequest)(nil),  // 15: utlxe.v1.UnloadTransformationRequest
	(*UnloadTransformationResponse)(nil), // 16: utlxe.v1.UnloadTransformationResponse
	(*HealthRequest)(nil),                // 17: utlxe.v1.HealthRequest
	(*HealthResponse)(nil),               // 18: utlxe.v1.HealthResponse
	(*StdioEnvelope)(nil),                // 19: utlxe.v1.StdioEnvelope
	nil,                                  // 20: utlxe.v1.LoadTransformationRequest.ConfigEntry
	nil,                                  // 21: utlxe.v1.ExecuteRequest.NamedInputsEntry
	nil,                                  // 22: utlxe.v1.BatchItem.NamedInputsEntry
}
var file_utlxe_v1_utlxe_proto_depIdxs = []int32{
	20, // 0: utlxe.v1.LoadTransformationRequest.config:type_name -> utlxe.v1.LoadTransformationRequest.ConfigEntry
	8,  // 1: utlxe.v1.LoadTransformationResponse.warnings:type_name -> utlxe.v1.ValidationError
	5,  // 2: utlxe.v1.LoadTransformationResponse.metrics:type_name -> utlxe.v1.LoadMetrics
	21, // 3: utlxe.v1.ExecuteRequest.named_inputs:type_name -> utlxe.v1.ExecuteRequest.NamedInputsEntry
	0,  // 4: utlxe.v1.ExecuteResponse.error_class:type_name -> utlxe.v1.ErrorClass
	8,  // 5: utlxe.v1.ExecuteResponse.validation_errors:type_name -> utlxe.v1.ValidationError
	9,  // 6: utlxe.v1.ExecuteResponse.metrics:type_name -> utlxe.v1.ExecuteMetrics
	1,  // 7: utlxe.v1.ExecuteResponse.error_phase:type_name -> utlxe.v1.ErrorPhase
	11, // 8: utlxe.v1.ExecuteBatchRequest.items:type_name -> utlxe.v1.BatchItem
	22, // 9: utlxe.v1.BatchItem.named_inputs:type_name -> utlxe.v1.BatchItem.NamedInputsEntry
	7,  // 10: utlxe.v1.ExecuteBatchResponse.results:type_name -> utlxe.v1.ExecuteResponse
	0,  // 11: utlxe.v1.ExecutePipelineResponse.error_class:type_name -> utlxe.v1.ErrorClass
	1,  // 12: utlxe.v1.ExecutePipelineResponse.error_phase:type_name -> utlxe.v1.ErrorPhase
	8,  // 13: utlxe.v1.ExecutePipelineResponse.validation_errors:type_name -> utlxe.v1.ValidationError
	2,  // 14: utlxe.v1.StdioEnvelope.type:type_name -> utlxe.v1.MessageType
	3,  // 15: utlxe.v1.UtlxeService.LoadTransformation:input_type -> utlxe.v1.LoadTransformationRequest
	6,  // 16: utlxe.v1.UtlxeService.Execute:input_type -> utlxe.v1.ExecuteRequest
	10, // 17: utlxe.v1.UtlxeService.ExecuteBatch:input_type -> utlxe.v1.ExecuteBatchRequest
	15, // 18: utlxe.v1.UtlxeService.UnloadTransformation:input_type -> utlxe.v1.UnloadTransformationRequest
	13, // 19: utlxe.v1.UtlxeService.ExecutePipeline:input_type -> utlxe.v1.ExecutePipelineRequest
	17, // 20: utlxe.v1.UtlxeService.Health:input_type -> utlxe.v1.HealthRequest
	4,  // 21: utlxe.v1.UtlxeService.LoadTransformation:output_type -> utlxe.v1.LoadTransformationResponse
	7,  // 22: utlxe.v1.UtlxeService.Execute:output_type -> utlxe.v1.ExecuteResponse
	12, // 23: utlxe.v1.UtlxeService.ExecuteBatch:output_type -> utlxe.v1.ExecuteBatchResponse
	16, // 24: utlxe.v1.UtlxeService.UnloadTransformation:output_type -> utlxe.v1.UnloadTransformationResponse
	14, // 25: utlxe.v1.UtlxeService.ExecutePipeline:output_type -> utlxe.v1.ExecutePipelineResponse
	18, // 26: utlxe.v1.UtlxeService.Health:output_type -> utlxe.v1.HealthResponse
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_utlxe_v1_utlxe_proto_init() }
func file_utlxe_v1_utlxe_proto_init() {
	if File_utlxe_v1_utlxe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utlxe_v1_utlxe_proto_rawDesc), len(file_utlxe_v1_utlxe_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_utlxe_v1_utlxe_proto_goTypes,
		DependencyIndexes: file_utlxe_v1_utlxe_proto_depIdxs,
		EnumInfos:         file_utlxe_v1_utlxe_proto_enumTypes,
		MessageInfos:      file_utlxe_v1_utlxe_proto_msgTypes,
	}.Build()
	File_utlxe_v1_utlxe_proto = out.File
	file_utlxe_v1_utlxe_proto_goTypes = nil
	file_utlxe_v1_utlxe_proto_depIdxs = nil
}
