= Engine Lifecycle: Design-Time, Init-Time, Runtime

== The Three Phases

Every UTL-X transformation goes through three distinct phases. Understanding them is key to performance tuning, debugging, and choosing the right execution strategy.

=== Phase 1: Design-Time
// - WHERE: developer's laptop, VS Code + utlxd
// - WHEN: while writing the transformation
// - WHAT HAPPENS:
//   1. Developer writes .utlx file
//   2. utlxd parses the source (ANTLR grammar → AST)
//   3. IDE shows syntax errors, autocompletion, type hints
//   4. Live preview: transformation runs on sample data
//   5. Schema-to-schema mapping (if using the visual mapper)
//   6. Scaffolding: generate skeleton from input/output schemas
//
// - COST: human time (minutes to hours per transformation)
// - OPTIMIZATION: good IDE, schema-driven development, reusable patterns
//
// Design-time artifacts:
//   .utlx file (transformation source)
//   .yaml config (engine configuration)
//   schemas (input/output validation)

=== Phase 2: Init-Time (Load / Compile)
// - WHERE: utlxe engine, at startup or on hot-reload
// - WHEN: when a transformation is loaded (startup, API call, bundle load)
// - WHAT HAPPENS:
//   1. Parse .utlx source → AST (same parser as design-time)
//   2. Resolve schemas (if referenced)
//   3. Strategy selection:
//      - TEMPLATE: nothing more — AST is ready to interpret
//      - COPY: build skeleton DOM from output schema, pre-allocate object pool
//      - COMPILED: AST → JVM bytecode via ASM (compilation cache, SHA256 key)
//      - AUTO: has schema? → COPY, no schema? → TEMPLATE
//   4. Register transformation in the registry (ConcurrentHashMap)
//   5. Transformation is now ready to accept messages
//
// - COST: milliseconds (TEMPLATE) to seconds (COMPILED, first time)
// - OPTIMIZATION:
//   - COMPILED: compilation cache (SHA256) — only compiles once per unique source
//   - COPY: skeleton built once, pooled (ConcurrentLinkedQueue, 32 slots)
//   - Bundle loading: all transforms loaded at startup, no per-request init
//
// Init-time is the MOST IMPORTANT phase for performance:
//   - A slow init is paid once
//   - A slow runtime is paid per message (thousands/millions of times)

=== Phase 3: Runtime (Execute)
// - WHERE: utlxe engine, per incoming message
// - WHEN: every time a message arrives (HTTP request, Dapr input, gRPC call)
// - WHAT HAPPENS:
//   1. Parse input data (XML/JSON/CSV/YAML → UDM)
//   2. Pre-validation (if schema configured)
//   3. Execute transformation:
//      - TEMPLATE: walk AST, evaluate expressions (interpreter)
//      - COPY: clone skeleton, fill values from input (fast path)
//      - COMPILED: call generated bytecode (JVM-optimized)
//   4. Post-validation (if schema configured)
//   5. Serialize output (UDM → target format)
//   6. Return result
//
// - COST: 1-50ms per message (depends on message size and complexity)
// - OPTIMIZATION:
//   - COMPILED: 2-5x faster than TEMPLATE for complex transformations
//   - COPY: fastest for schema-driven, object-pool avoids GC pressure
//   - Worker threads: concurrent execution (8-128 workers)
//   - Back-pressure: ArrayBlockingQueue prevents overload

== Phase Diagram

// ┌─────────────────────────────────────────────────────────────┐
// │                    DESIGN-TIME                               │
// │  Developer → VS Code → utlxd → .utlx file                  │
// │  (minutes to hours, human-driven)                            │
// └──────────────────────┬──────────────────────────────────────┘
//                        │ .utlx file + schemas
//                        ▼
// ┌─────────────────────────────────────────────────────────────┐
// │                    INIT-TIME                                 │
// │  utlxe loads .utlx → parse → compile/prepare → register    │
// │  (milliseconds to seconds, once per transformation)          │
// │                                                              │
// │  Strategy selection:                                         │
// │    TEMPLATE: AST ready (instant)                             │
// │    COPY: build skeleton + object pool (fast)                 │
// │    COMPILED: AST → bytecode (slow first time, cached)        │
// └──────────────────────┬──────────────────────────────────────┘
//                        │ registered transformation
//                        ▼
// ┌─────────────────────────────────────────────────────────────┐
// │                    RUNTIME                                   │
// │  Message arrives → parse → validate → transform → serialize  │
// │  (1-50ms per message, millions of times)                     │
// │                                                              │
// │  8-128 workers process concurrently                          │
// │  Back-pressure: queue full → caller waits                    │
// └─────────────────────────────────────────────────────────────┘

== How Strategies Affect Each Phase

// | Strategy | Init-Time | Runtime (per msg) | Best For |
// |----------|-----------|-------------------|----------|
// | TEMPLATE | Instant (parse only) | Slower (interpret AST) | Development, simple transforms |
// | COPY | Fast (build skeleton) | Fast (clone + fill) | Schema-driven, high throughput |
// | COMPILED | Slow first (bytecode gen) | Fastest (JVM-optimized) | Maximum throughput, complex logic |
// | AUTO | Depends on schema | Depends on schema | Production default |
//
// The hybrid: COPY + COMPILED
// - COPY builds the skeleton (init-time)
// - COMPILED generates bytecode for the fill logic (init-time)
// - Runtime: clone skeleton + run compiled fill → fastest possible path

== Worker Threading Model
// - Worker pool: fixed-size thread pool (--workers N)
// - Each worker: independent transformation execution
// - No shared mutable state between workers (thread-safe)
// - Back-pressure: ArrayBlockingQueue with CallerRunsPolicy
//   - Queue full → calling thread executes the work itself
//   - Prevents OOM from unbounded queue growth
//   - Natural flow control: producer slows down when workers are busy
//
// Tuning:
// - 8 workers per vCPU is a good starting point
// - Increase for I/O-heavy transformations (waiting on downstream HTTP)
// - Decrease for memory-heavy transformations (large XML documents)
// - Monitor via Prometheus: worker_utilization, queue_depth
