import { defineConfig } from 'vitepress'
import { fileURLToPath, URL } from 'node:url'
import fs from 'node:fs'
import path from 'node:path'

/**
 * Build the Guide sidebar automatically from the converted chapter files in `site/guide/`.
 * Order = filename order (ch00, ch01, …). Title = the first `# ` heading, else the slug.
 * Re-running `npm run convert` regenerates those files; the sidebar follows automatically.
 */
function guideSidebar() {
  const dir = fileURLToPath(new URL('../guide', import.meta.url))
  if (!fs.existsSync(dir)) return []
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.md'))
    .sort()
    .map(f => {
      const slug = f.replace(/\.md$/, '')
      const content = fs.readFileSync(path.join(dir, f), 'utf-8')
      const m = content.match(/^#\s+(.+?)\s*$/m)
      return { text: m ? m[1] : slug, link: `/guide/${slug}` }
    })
}

/**
 * Reference sidebar = the per-function stdlib pages, grouped by category and
 * collapsed. Generated by `npm run stdlib` into reference/.sidebar.json so the
 * 600+ functions don't have to be hand-listed here.
 */
function referenceSidebar() {
  const file = fileURLToPath(new URL('../reference/.sidebar.json', import.meta.url))
  const groups = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf-8')) : []
  return [{ text: 'Standard Library', link: '/reference/stdlib' }, ...groups]
}

// base/outDir are env-driven so the SAME source builds two targets from one config:
//   web (utlx-lang.org): npm run build      → base '/'           → .vitepress/dist
//   in-IDE help        : npm run build:ide  → base '/utlx-docs/' → .vitepress/dist-ide
// (the in-IDE build is served same-origin under /utlx-docs/ through Theia's backend.)
const BASE = process.env.DOCS_BASE || '/'

export default defineConfig({
  base: BASE,
  outDir: process.env.DOCS_OUTDIR || '.vitepress/dist',
  // NOTE: build-stdlib.mjs emits RAW-HTML content links that are root-absolute (/reference/…, /guide/…)
  // and bypass VitePress's link base-rewriting (Markdown + theme links only). For the sub-path IDE build
  // those are fixed AFTER the build by scripts/fix-ide-base.mjs (rewrites dist-ide HTML + JS). The web
  // build (base '/') needs nothing. (Doing it post-build is more reliable than transformHtml/renderChunk,
  // which miss the client JS chunks.)
  title: 'UTL-X',
  description: 'UTL-X — One Language, All Formats. The complete language reference and standard library.',
  lang: 'en-US',
  cleanUrls: true,
  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/ch00-preface' },
      { text: 'Stdlib Reference', link: '/reference/stdlib' },
      { text: 'utlx.dev', link: 'https://utlx.dev' }
    ],
    sidebar: {
      '/guide/': [{ text: 'UTL-X — One Language, All Formats', items: guideSidebar() }],
      '/reference/': referenceSidebar()
    },
    search: { provider: 'local' },
    socialLinks: [{ icon: 'github', link: 'https://github.com/grauwen/utl-x' }],
    footer: {
      message: 'Released under AGPL-3.0.',
      copyright: '© Marcel A. Grauwen'
    }
  }
})
