package org.apache.utlx.engine.strategy.compiled

import org.apache.utlx.core.ast.*
import org.apache.utlx.core.udm.UDM
import org.objectweb.asm.*
import org.objectweb.asm.Opcodes.*
import org.slf4j.LoggerFactory
import java.security.MessageDigest
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicLong

/**
 * Compiles a UTL-X AST body expression to JVM bytecode using ASM.
 *
 * Generates a class implementing TransformFunction with a single execute() method.
 * The generated bytecode calls RuntimeOps static methods for operations and
 * stdlib functions for UTL-X function calls.
 *
 * Supports (Phase 1): literals, object/array construction, property access,
 * binary operators, conditionals, let bindings, variable references.
 *
 * Falls back to interpreter for unsupported nodes (returns null from compile()).
 */
class ASTCompiler {

    private val logger = LoggerFactory.getLogger(ASTCompiler::class.java)

    companion object {
        private val counter = AtomicLong(0)
        // Compilation cache: SHA256 of source → compiled TransformFunction
        private val compilationCache = ConcurrentHashMap<String, TransformFunction>()

        private const val RUNTIME_OPS = "org/apache/utlx/engine/strategy/compiled/RuntimeOps"
        private const val UDM_TYPE = "org/apache/utlx/core/udm/UDM"
        private const val UDM_DESC = "Lorg/apache/utlx/core/udm/UDM;"
        private const val UDM_SCALAR = "org/apache/utlx/core/udm/UDM\$Scalar"
        private const val UDM_OBJECT = "org/apache/utlx/core/udm/UDM\$Object"
        private const val UDM_ARRAY = "org/apache/utlx/core/udm/UDM\$Array"
        private const val MAP_TYPE = "java/util/Map"
        private const val TRANSFORM_FN = "org/apache/utlx/engine/strategy/compiled/TransformFunction"
    }

    /**
     * Compile a program's body expression to a TransformFunction.
     * Returns null if the expression contains unsupported nodes (caller should fall back to interpreter).
     */
    fun compile(program: Program): TransformFunction? {
        // Check if the expression is compilable
        if (!isCompilable(program.body)) {
            logger.info("Expression contains unsupported nodes — falling back to interpreter")
            return null
        }

        // Check compilation cache — skip bytecode generation if same source was compiled before
        val sourceHash = program.body.toString().let { src ->
            MessageDigest.getInstance("SHA-256").digest(src.toByteArray()).joinToString("") { "%02x".format(it) }
        }
        compilationCache[sourceHash]?.let { cached ->
            logger.debug("Compilation cache hit for hash {}", sourceHash.take(12))
            return cached
        }

        val className = "utlx/compiled/Transform_${counter.incrementAndGet()}"

        val cw = ClassWriter(ClassWriter.COMPUTE_FRAMES or ClassWriter.COMPUTE_MAXS)
        cw.visit(V17, ACC_PUBLIC or ACC_SUPER, className, null, "java/lang/Object",
            arrayOf(TRANSFORM_FN))

        // Default constructor
        val init = cw.visitMethod(ACC_PUBLIC, "<init>", "()V", null, null)
        init.visitCode()
        init.visitVarInsn(ALOAD, 0)
        init.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false)
        init.visitInsn(RETURN)
        init.visitMaxs(1, 1)
        init.visitEnd()

        // execute(Map<String, UDM>): UDM
        val mv = cw.visitMethod(ACC_PUBLIC, "execute",
            "(Ljava/util/Map;)$UDM_DESC", null, null)
        mv.visitCode()

        // Local variable slots:
        // 0 = this
        // 1 = inputs (Map<String, UDM>)
        // 2+ = let bindings
        val ctx = CompileContext(mv, localSlot = 2, classWriter = cw, className = className)

        // Compile the body expression — leaves result UDM on stack
        compileExpression(ctx, program.body)

        mv.visitInsn(ARETURN)
        mv.visitMaxs(0, 0) // COMPUTE_MAXS handles this
        mv.visitEnd()

        cw.visitEnd()
        val bytecode = cw.toByteArray()

        // Load and instantiate
        val loader = BytecodeClassLoader(ASTCompiler::class.java.classLoader)
        val clazz = loader.defineClass(className.replace('/', '.'), bytecode)
        val instance = clazz.getDeclaredConstructor().newInstance()

        val transformFunction = instance as TransformFunction
        compilationCache[sourceHash] = transformFunction
        logger.debug("Compiled transformation to {} ({} bytes, cached as {})", className, bytecode.size, sourceHash.take(12))
        return transformFunction
    }

    // =========================================================================
    // Compilability check — can we compile this expression?
    // =========================================================================

    private fun isCompilable(expr: Expression): Boolean {
        return when (expr) {
            is Expression.StringLiteral -> true
            is Expression.NumberLiteral -> true
            is Expression.BooleanLiteral -> true
            is Expression.NullLiteral -> true
            is Expression.Identifier -> true
            is Expression.ObjectLiteral -> {
                expr.properties.all { (it.key != null || it.isSpread) && it.computedKey == null && isCompilable(it.value) } &&
                    expr.letBindings.all { isCompilable(it.value) }
            }
            is Expression.ArrayLiteral -> expr.elements.all { isCompilable(it) }
            is Expression.MemberAccess -> isCompilable(expr.target)
            is Expression.IndexAccess -> isCompilable(expr.target) && isCompilable(expr.index)
            is Expression.BinaryOp -> isCompilable(expr.left) && isCompilable(expr.right)
            is Expression.UnaryOp -> isCompilable(expr.operand)
            is Expression.Conditional -> isCompilable(expr.condition) &&
                isCompilable(expr.thenBranch) && (expr.elseBranch?.let { isCompilable(it) } ?: true)
            is Expression.Ternary -> isCompilable(expr.condition) &&
                isCompilable(expr.thenExpr) && isCompilable(expr.elseExpr)
            is Expression.LetBinding -> isCompilable(expr.value)
            is Expression.FunctionCall -> {
                val fn = expr.function
                fn is Expression.Identifier && expr.arguments.all { isCompilable(it) }
            }
            is Expression.Block -> expr.expressions.all { isCompilable(it) }
            is Expression.Lambda -> isCompilable(expr.body)
            is Expression.Pipe -> isCompilable(expr.source) && isCompilable(expr.target)
            is Expression.SafeNavigation -> isCompilable(expr.target)
            is Expression.Match -> expr.cases.all { isCompilable(it.expression) && (it.guard?.let { g -> isCompilable(g) } ?: true) }
            is Expression.TryCatch -> isCompilable(expr.tryBlock) && isCompilable(expr.catchBlock)
            is Expression.SpreadElement -> isCompilable(expr.expression)
            is Expression.TemplateApplication -> isCompilable(expr.selector)
        }
    }

    // =========================================================================
    // Expression compilation — each method leaves one UDM on the stack
    // =========================================================================

    private data class CompileContext(
        val mv: MethodVisitor,
        var localSlot: Int,
        val locals: MutableMap<String, Int> = mutableMapOf(),
        val classWriter: ClassWriter? = null,
        val className: String? = null,
        var lambdaCounter: Int = 0
    ) {
        fun allocLocal(name: String): Int {
            val slot = localSlot++
            locals[name] = slot
            return slot
        }

        fun nextLambdaName(): String = "lambda_${lambdaCounter++}"
    }

    private fun compileExpression(ctx: CompileContext, expr: Expression) {
        when (expr) {
            is Expression.StringLiteral -> compileStringLiteral(ctx, expr)
            is Expression.NumberLiteral -> compileNumberLiteral(ctx, expr)
            is Expression.BooleanLiteral -> compileBooleanLiteral(ctx, expr)
            is Expression.NullLiteral -> compileNullLiteral(ctx)
            is Expression.Identifier -> compileIdentifier(ctx, expr)
            is Expression.ObjectLiteral -> compileObjectLiteral(ctx, expr)
            is Expression.ArrayLiteral -> compileArrayLiteral(ctx, expr)
            is Expression.MemberAccess -> compileMemberAccess(ctx, expr)
            is Expression.IndexAccess -> compileIndexAccess(ctx, expr)
            is Expression.BinaryOp -> compileBinaryOp(ctx, expr)
            is Expression.UnaryOp -> compileUnaryOp(ctx, expr)
            is Expression.Conditional -> compileConditional(ctx, expr)
            is Expression.Ternary -> compileTernary(ctx, expr)
            is Expression.LetBinding -> compileLetBinding(ctx, expr)
            is Expression.FunctionCall -> compileFunctionCall(ctx, expr)
            is Expression.Block -> compileBlock(ctx, expr)
            is Expression.Lambda -> compileLambda(ctx, expr)
            is Expression.Pipe -> compilePipe(ctx, expr)
            is Expression.SafeNavigation -> compileSafeNavigation(ctx, expr)
            is Expression.TryCatch -> compileTryCatch(ctx, expr)
            is Expression.SpreadElement -> compileExpression(ctx, expr.expression) // spread handled by parent
            is Expression.Match -> compileMatch(ctx, expr)
            is Expression.TemplateApplication -> compileExpression(ctx, expr.selector) // passthrough
        }
    }

    // ── Literals ──

    private fun compileStringLiteral(ctx: CompileContext, expr: Expression.StringLiteral) {
        ctx.mv.visitTypeInsn(NEW, UDM_SCALAR)
        ctx.mv.visitInsn(DUP)
        ctx.mv.visitLdcInsn(expr.value)
        ctx.mv.visitMethodInsn(INVOKESPECIAL, UDM_SCALAR, "<init>",
            "(Ljava/lang/Object;)V", false)
    }

    private fun compileNumberLiteral(ctx: CompileContext, expr: Expression.NumberLiteral) {
        ctx.mv.visitLdcInsn(expr.value)
        ctx.mv.visitMethodInsn(INVOKESTATIC, "java/lang/Double", "valueOf",
            "(D)Ljava/lang/Double;", false)
        // UDM.Scalar(value)
        ctx.mv.visitTypeInsn(NEW, UDM_SCALAR)
        ctx.mv.visitInsn(DUP_X1)
        ctx.mv.visitInsn(SWAP)
        ctx.mv.visitMethodInsn(INVOKESPECIAL, UDM_SCALAR, "<init>",
            "(Ljava/lang/Object;)V", false)
    }

    private fun compileBooleanLiteral(ctx: CompileContext, expr: Expression.BooleanLiteral) {
        ctx.mv.visitLdcInsn(if (expr.value) 1 else 0)
        ctx.mv.visitMethodInsn(INVOKESTATIC, "java/lang/Boolean", "valueOf",
            "(Z)Ljava/lang/Boolean;", false)
        ctx.mv.visitTypeInsn(NEW, UDM_SCALAR)
        ctx.mv.visitInsn(DUP_X1)
        ctx.mv.visitInsn(SWAP)
        ctx.mv.visitMethodInsn(INVOKESPECIAL, UDM_SCALAR, "<init>",
            "(Ljava/lang/Object;)V", false)
    }

    private fun compileNullLiteral(ctx: CompileContext) {
        ctx.mv.visitTypeInsn(NEW, UDM_SCALAR)
        ctx.mv.visitInsn(DUP)
        ctx.mv.visitInsn(ACONST_NULL)
        ctx.mv.visitMethodInsn(INVOKESPECIAL, UDM_SCALAR, "<init>",
            "(Ljava/lang/Object;)V", false)
    }

    // ── Variables ──

    private fun compileIdentifier(ctx: CompileContext, expr: Expression.Identifier) {
        val name = expr.name
        val localSlot = ctx.locals[name]
        if (localSlot != null) {
            // Local variable (let binding)
            ctx.mv.visitVarInsn(ALOAD, localSlot)
        } else {
            // Input variable — look up in inputs map (arg 1)
            ctx.mv.visitVarInsn(ALOAD, 1) // inputs map
            ctx.mv.visitLdcInsn(name)
            ctx.mv.visitMethodInsn(INVOKEINTERFACE, MAP_TYPE, "get",
                "(Ljava/lang/Object;)Ljava/lang/Object;", true)
            ctx.mv.visitTypeInsn(CHECKCAST, UDM_TYPE)
        }
    }

    // ── Property access ──

    private fun compileMemberAccess(ctx: CompileContext, expr: Expression.MemberAccess) {
        compileExpression(ctx, expr.target)
        ctx.mv.visitLdcInsn(expr.property)
        if (expr.isAttribute) {
            ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "getAttribute",
                "(${UDM_DESC}Ljava/lang/String;)$UDM_DESC", false)
        } else {
            ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "getProperty",
                "(${UDM_DESC}Ljava/lang/String;)$UDM_DESC", false)
        }
    }

    private fun compileIndexAccess(ctx: CompileContext, expr: Expression.IndexAccess) {
        compileExpression(ctx, expr.target)
        // For now, only support integer index literals
        if (expr.index is Expression.NumberLiteral) {
            ctx.mv.visitLdcInsn((expr.index as Expression.NumberLiteral).value.toInt())
        } else {
            compileExpression(ctx, expr.index)
            // Convert UDM number to int
            ctx.mv.visitMethodInsn(INVOKEVIRTUAL, UDM_TYPE, "asNumber", "()D", false)
            ctx.mv.visitInsn(D2I)
        }
        ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "getIndex",
            "(${UDM_DESC}I)$UDM_DESC", false)
    }

    private fun compileSafeNavigation(ctx: CompileContext, expr: Expression.SafeNavigation) {
        compileExpression(ctx, expr.target)
        // Check if null, if so return null, otherwise access property
        val nullLabel = Label()
        val endLabel = Label()
        ctx.mv.visitInsn(DUP)
        ctx.mv.visitMethodInsn(INVOKEVIRTUAL, UDM_TYPE, "isNull", "()Z", false)
        ctx.mv.visitJumpInsn(IFNE, nullLabel)
        // Not null — access property
        ctx.mv.visitLdcInsn(expr.property)
        ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "getProperty",
            "(${UDM_DESC}Ljava/lang/String;)$UDM_DESC", false)
        ctx.mv.visitJumpInsn(GOTO, endLabel)
        // Null — return null
        ctx.mv.visitLabel(nullLabel)
        ctx.mv.visitInsn(POP) // remove the dup'd null
        compileNullLiteral(ctx)
        ctx.mv.visitLabel(endLabel)
    }

    // ── Object/Array construction ──

    private fun compileObjectLiteral(ctx: CompileContext, expr: Expression.ObjectLiteral) {
        // Process let bindings first
        for (binding in expr.letBindings) {
            compileExpression(ctx, binding.value)
            val slot = ctx.allocLocal(binding.name)
            ctx.mv.visitVarInsn(ASTORE, slot)
        }

        // Separate regular properties from spread properties
        val regularProps = expr.properties.filter { it.key != null && !it.isSpread }
        val hasSpread = expr.properties.any { it.isSpread }

        // Build the base object from regular properties
        val count = regularProps.size

        // Create String[] for keys
        ctx.mv.visitLdcInsn(count)
        ctx.mv.visitTypeInsn(ANEWARRAY, "java/lang/String")
        for (i in regularProps.indices) {
            ctx.mv.visitInsn(DUP)
            ctx.mv.visitLdcInsn(i)
            ctx.mv.visitLdcInsn(regularProps[i].key)
            ctx.mv.visitInsn(AASTORE)
        }

        // Create UDM[] for values
        ctx.mv.visitLdcInsn(count)
        ctx.mv.visitTypeInsn(ANEWARRAY, UDM_TYPE)
        for (i in regularProps.indices) {
            ctx.mv.visitInsn(DUP)
            ctx.mv.visitLdcInsn(i)
            compileExpression(ctx, regularProps[i].value)
            ctx.mv.visitInsn(AASTORE)
        }

        // RuntimeOps.buildObject(keys, values)
        ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "buildObject",
            "([Ljava/lang/String;[$UDM_DESC)$UDM_DESC", false)

        // Merge spread properties into the object
        if (hasSpread) {
            for (prop in expr.properties) {
                if (prop.isSpread) {
                    compileExpression(ctx, prop.value)
                    ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "spreadIntoObject",
                        "(${UDM_DESC}${UDM_DESC})$UDM_DESC", false)
                }
            }
        }
    }

    private fun compileArrayLiteral(ctx: CompileContext, expr: Expression.ArrayLiteral) {
        val count = expr.elements.size
        ctx.mv.visitLdcInsn(count)
        ctx.mv.visitTypeInsn(ANEWARRAY, UDM_TYPE)
        for (i in expr.elements.indices) {
            ctx.mv.visitInsn(DUP)
            ctx.mv.visitLdcInsn(i)
            compileExpression(ctx, expr.elements[i])
            ctx.mv.visitInsn(AASTORE)
        }
        ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "buildArray",
            "([$UDM_DESC)$UDM_DESC", false)
    }

    // ── Binary operators ──

    private fun compileBinaryOp(ctx: CompileContext, expr: Expression.BinaryOp) {
        // Short-circuit for && and ||
        if (expr.operator == BinaryOperator.AND || expr.operator == BinaryOperator.OR) {
            compileShortCircuit(ctx, expr)
            return
        }

        compileExpression(ctx, expr.left)
        compileExpression(ctx, expr.right)

        val method = when (expr.operator) {
            BinaryOperator.PLUS -> "add"
            BinaryOperator.MINUS -> "subtract"
            BinaryOperator.MULTIPLY -> "multiply"
            BinaryOperator.DIVIDE -> "divide"
            BinaryOperator.MODULO -> "modulo"
            BinaryOperator.EQUAL -> "equal"
            BinaryOperator.NOT_EQUAL -> "notEqual"
            BinaryOperator.GREATER_THAN -> "greaterThan"
            BinaryOperator.GREATER_EQUAL -> "greaterEqual"
            BinaryOperator.LESS_THAN -> "lessThan"
            BinaryOperator.LESS_EQUAL -> "lessEqual"
            BinaryOperator.NULLISH_COALESCE -> "nullishCoalesce"
            else -> throw UnsupportedOperationException("Operator: ${expr.operator}")
        }

        ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, method,
            "($UDM_DESC$UDM_DESC)$UDM_DESC", false)
    }

    private fun compileShortCircuit(ctx: CompileContext, expr: Expression.BinaryOp) {
        val endLabel = Label()
        compileExpression(ctx, expr.left)

        if (expr.operator == BinaryOperator.AND) {
            // If left is falsy, return left (short-circuit)
            ctx.mv.visitInsn(DUP)
            ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "isTruthy",
                "($UDM_DESC)Z", false)
            ctx.mv.visitJumpInsn(IFEQ, endLabel) // left is falsy → keep it on stack
            ctx.mv.visitInsn(POP) // discard left, evaluate right
            compileExpression(ctx, expr.right)
        } else {
            // OR: if left is truthy, return left (short-circuit)
            ctx.mv.visitInsn(DUP)
            ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "isTruthy",
                "($UDM_DESC)Z", false)
            ctx.mv.visitJumpInsn(IFNE, endLabel) // left is truthy → keep it on stack
            ctx.mv.visitInsn(POP) // discard left, evaluate right
            compileExpression(ctx, expr.right)
        }

        ctx.mv.visitLabel(endLabel)
    }

    // ── Unary operators ──

    private fun compileUnaryOp(ctx: CompileContext, expr: Expression.UnaryOp) {
        compileExpression(ctx, expr.operand)
        val method = when (expr.operator) {
            UnaryOperator.NOT -> "not"
            UnaryOperator.MINUS -> "negate"
        }
        ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, method,
            "($UDM_DESC)$UDM_DESC", false)
    }

    // ── Conditionals ──

    private fun compileConditional(ctx: CompileContext, expr: Expression.Conditional) {
        val elseLabel = Label()
        val endLabel = Label()

        compileExpression(ctx, expr.condition)
        ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "isTruthy",
            "($UDM_DESC)Z", false)
        ctx.mv.visitJumpInsn(IFEQ, elseLabel)

        // Then branch
        compileExpression(ctx, expr.thenBranch)
        ctx.mv.visitJumpInsn(GOTO, endLabel)

        // Else branch
        ctx.mv.visitLabel(elseLabel)
        val elseBranch = expr.elseBranch
        if (elseBranch != null) {
            compileExpression(ctx, elseBranch)
        } else {
            compileNullLiteral(ctx)
        }

        ctx.mv.visitLabel(endLabel)
    }

    private fun compileTernary(ctx: CompileContext, expr: Expression.Ternary) {
        val elseLabel = Label()
        val endLabel = Label()

        compileExpression(ctx, expr.condition)
        ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "isTruthy",
            "($UDM_DESC)Z", false)
        ctx.mv.visitJumpInsn(IFEQ, elseLabel)

        compileExpression(ctx, expr.thenExpr)
        ctx.mv.visitJumpInsn(GOTO, endLabel)

        ctx.mv.visitLabel(elseLabel)
        compileExpression(ctx, expr.elseExpr)

        ctx.mv.visitLabel(endLabel)
    }

    // ── Let bindings ──

    private fun compileLetBinding(ctx: CompileContext, expr: Expression.LetBinding) {
        compileExpression(ctx, expr.value)
        val slot = ctx.allocLocal(expr.name)
        ctx.mv.visitInsn(DUP) // keep value on stack (let binding is an expression that returns the value)
        ctx.mv.visitVarInsn(ASTORE, slot)
    }

    // ── Function calls ──

    private fun compileFunctionCall(ctx: CompileContext, expr: Expression.FunctionCall) {
        val fn = expr.function
        if (fn !is Expression.Identifier) {
            throw UnsupportedOperationException("Only direct function calls supported in compiled mode")
        }

        val funcName = fn.name
        val localSlot = ctx.locals[funcName]

        // Build argument list as UDM array
        val argList = {
            ctx.mv.visitLdcInsn(expr.arguments.size)
            ctx.mv.visitTypeInsn(ANEWARRAY, UDM_TYPE)
            for (i in expr.arguments.indices) {
                ctx.mv.visitInsn(DUP)
                ctx.mv.visitLdcInsn(i)
                compileExpression(ctx, expr.arguments[i])
                ctx.mv.visitInsn(AASTORE)
            }
            ctx.mv.visitMethodInsn(INVOKESTATIC, "java/util/Arrays", "asList",
                "([Ljava/lang/Object;)Ljava/util/List;", false)
        }

        if (localSlot != null) {
            // User-defined function: local variable holds a UDM.Lambda
            // Push: UDM (lambda), then List (args) → RuntimeOps.invokeLambda(UDM, List)
            ctx.mv.visitVarInsn(ALOAD, localSlot)
            argList()
            ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "invokeLambda",
                "(${UDM_DESC}Ljava/util/List;)$UDM_DESC", false)
        } else {
            // Stdlib function: push name, then args → StdlibDispatch.call(String, List)
            ctx.mv.visitLdcInsn(funcName)
            argList()
            ctx.mv.visitMethodInsn(INVOKESTATIC,
                "org/apache/utlx/engine/strategy/compiled/StdlibDispatch", "call",
                "(Ljava/lang/String;Ljava/util/List;)$UDM_DESC", false)
        }
    }

    // ── Block ──

    private fun compileBlock(ctx: CompileContext, expr: Expression.Block) {
        for (i in expr.expressions.indices) {
            compileExpression(ctx, expr.expressions[i])
            if (i < expr.expressions.size - 1) {
                ctx.mv.visitInsn(POP) // discard all but last
            }
        }
    }

    // ── Pipe ──

    private fun compilePipe(ctx: CompileContext, expr: Expression.Pipe) {
        // expr |> func(args...) desugars to func(expr, args...)
        val target = expr.target
        if (target is Expression.FunctionCall) {
            val fn = target.function
            if (fn is Expression.Identifier) {
                // Build: funcName(source, ...originalArgs)
                val allArgs = listOf(expr.source) + target.arguments
                val newCall = Expression.FunctionCall(fn, allArgs, expr.location)
                compileFunctionCall(ctx, newCall)
                return
            }
        }
        // Fallback: evaluate source, discard, evaluate target
        compileExpression(ctx, expr.source)
        ctx.mv.visitInsn(POP)
        compileExpression(ctx, expr.target)
    }

    // ── Lambda compilation ──

    /**
     * Compile a lambda expression.
     *
     * Generates a static method in the same class:
     *   static UDM lambda_N(List<UDM> args) {
     *       UDM param1 = args.get(0);
     *       UDM param2 = args.get(1);  // etc.
     *       return <compiled body>;
     *   }
     *
     * Then at the call site, constructs a UDM.Lambda via RuntimeOps.makeLambda().
     */
    private fun compileLambda(ctx: CompileContext, expr: Expression.Lambda) {
        val cw = ctx.classWriter
            ?: throw IllegalStateException("ClassWriter not available for lambda compilation")
        val className = ctx.className
            ?: throw IllegalStateException("className not available for lambda compilation")

        val lambdaName = ctx.nextLambdaName()

        // Generate static method: static UDM lambda_N(List<UDM>)
        val lambdaMv = cw.visitMethod(
            ACC_PUBLIC or ACC_STATIC, lambdaName,
            "(Ljava/util/List;)$UDM_DESC", null, null)
        lambdaMv.visitCode()

        // Create a new context for the lambda body
        // Local slot 0 = args (List<UDM>)
        val lambdaCtx = CompileContext(lambdaMv, localSlot = 1,
            locals = mutableMapOf(), classWriter = cw, className = className)

        // Bind parameters: extract from args list by index
        for (i in expr.parameters.indices) {
            val paramName = expr.parameters[i].name
            val slot = lambdaCtx.allocLocal(paramName)
            lambdaMv.visitVarInsn(ALOAD, 0) // args list
            lambdaMv.visitLdcInsn(i)
            lambdaMv.visitMethodInsn(INVOKEINTERFACE, "java/util/List", "get",
                "(I)Ljava/lang/Object;", true)
            lambdaMv.visitTypeInsn(CHECKCAST, UDM_TYPE)
            lambdaMv.visitVarInsn(ASTORE, slot)
        }

        // Compile lambda body
        compileExpression(lambdaCtx, expr.body)

        lambdaMv.visitInsn(ARETURN)
        lambdaMv.visitMaxs(0, 0)
        lambdaMv.visitEnd()

        // At the call site: RuntimeOps.makeLambda(ThisClass.class, "lambda_N")
        // Push the class reference
        ctx.mv.visitLdcInsn(org.objectweb.asm.Type.getObjectType(className))
        ctx.mv.visitLdcInsn(lambdaName)
        ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "makeLambda",
            "(Ljava/lang/Class;Ljava/lang/String;)$UDM_DESC", false)
    }

    // ── Try/Catch ──

    private fun compileTryCatch(ctx: CompileContext, expr: Expression.TryCatch) {
        val tryStart = Label()
        val tryEnd = Label()
        val catchStart = Label()
        val endLabel = Label()

        ctx.mv.visitTryCatchBlock(tryStart, tryEnd, catchStart, "java/lang/Exception")

        // Try block
        ctx.mv.visitLabel(tryStart)
        compileExpression(ctx, expr.tryBlock)
        ctx.mv.visitLabel(tryEnd)
        ctx.mv.visitJumpInsn(GOTO, endLabel)

        // Catch block
        ctx.mv.visitLabel(catchStart)
        // Exception is on stack — store in local if error variable is declared
        val errorVar = expr.errorVariable
        if (errorVar != null) {
            // Convert exception to UDM.Scalar(message)
            ctx.mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/Exception", "getMessage",
                "()Ljava/lang/String;", false)
            ctx.mv.visitTypeInsn(NEW, UDM_SCALAR)
            ctx.mv.visitInsn(DUP_X1)
            ctx.mv.visitInsn(SWAP)
            ctx.mv.visitMethodInsn(INVOKESPECIAL, UDM_SCALAR, "<init>",
                "(Ljava/lang/Object;)V", false)
            val slot = ctx.allocLocal(errorVar)
            ctx.mv.visitVarInsn(ASTORE, slot)
        } else {
            ctx.mv.visitInsn(POP) // discard exception
        }
        compileExpression(ctx, expr.catchBlock)

        ctx.mv.visitLabel(endLabel)
    }

    // ── Match ──

    private fun compileMatch(ctx: CompileContext, expr: Expression.Match) {
        // Evaluate the match value once, store in local
        compileExpression(ctx, expr.value)
        val matchSlot = ctx.localSlot++
        ctx.mv.visitVarInsn(ASTORE, matchSlot)

        val endLabel = Label()

        for (matchCase in expr.cases) {
            val nextCaseLabel = Label()

            when (val pattern = matchCase.pattern) {
                is Pattern.Wildcard -> {
                    // Wildcard always matches — no condition check
                }
                is Pattern.Literal -> {
                    // Compare match value against literal
                    ctx.mv.visitVarInsn(ALOAD, matchSlot)
                    when (val litVal = pattern.value) {
                        is String -> {
                            ctx.mv.visitTypeInsn(NEW, UDM_SCALAR)
                            ctx.mv.visitInsn(DUP)
                            ctx.mv.visitLdcInsn(litVal)
                            ctx.mv.visitMethodInsn(INVOKESPECIAL, UDM_SCALAR, "<init>",
                                "(Ljava/lang/Object;)V", false)
                        }
                        is Number -> {
                            ctx.mv.visitTypeInsn(NEW, UDM_SCALAR)
                            ctx.mv.visitInsn(DUP)
                            ctx.mv.visitLdcInsn(litVal.toDouble())
                            ctx.mv.visitMethodInsn(INVOKESTATIC, "java/lang/Double", "valueOf",
                                "(D)Ljava/lang/Double;", false)
                            ctx.mv.visitMethodInsn(INVOKESPECIAL, UDM_SCALAR, "<init>",
                                "(Ljava/lang/Object;)V", false)
                        }
                        is Boolean -> {
                            ctx.mv.visitTypeInsn(NEW, UDM_SCALAR)
                            ctx.mv.visitInsn(DUP)
                            ctx.mv.visitLdcInsn(if (litVal) 1 else 0)
                            ctx.mv.visitMethodInsn(INVOKESTATIC, "java/lang/Boolean", "valueOf",
                                "(Z)Ljava/lang/Boolean;", false)
                            ctx.mv.visitMethodInsn(INVOKESPECIAL, UDM_SCALAR, "<init>",
                                "(Ljava/lang/Object;)V", false)
                        }
                        null -> compileNullLiteral(ctx)
                        else -> compileNullLiteral(ctx)
                    }
                    ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "equal",
                        "(${UDM_DESC}${UDM_DESC})$UDM_DESC", false)
                    ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "isTruthy",
                        "(${UDM_DESC})Z", false)
                    ctx.mv.visitJumpInsn(IFEQ, nextCaseLabel) // not equal → next case
                }
                is Pattern.Variable -> {
                    // Bind match value to variable name
                    ctx.mv.visitVarInsn(ALOAD, matchSlot)
                    val slot = ctx.allocLocal(pattern.name)
                    ctx.mv.visitVarInsn(ASTORE, slot)
                }
            }

            // Guard check (if present)
            val guard = matchCase.guard
            if (guard != null) {
                compileExpression(ctx, guard)
                ctx.mv.visitMethodInsn(INVOKESTATIC, RUNTIME_OPS, "isTruthy",
                    "(${UDM_DESC})Z", false)
                ctx.mv.visitJumpInsn(IFEQ, nextCaseLabel)
            }

            // Case body
            compileExpression(ctx, matchCase.expression)
            ctx.mv.visitJumpInsn(GOTO, endLabel)

            ctx.mv.visitLabel(nextCaseLabel)
        }

        // No case matched — return null
        compileNullLiteral(ctx)
        ctx.mv.visitLabel(endLabel)
    }

    // =========================================================================
    // Classloader
    // =========================================================================

    private class BytecodeClassLoader(parent: ClassLoader) : ClassLoader(parent) {
        fun defineClass(name: String, bytecode: ByteArray): Class<*> {
            return defineClass(name, bytecode, 0, bytecode.size)
        }
    }
}
