package org.apache.utlx.engine.strategy.compiled

import org.apache.utlx.core.udm.UDM

/**
 * Runtime operations called by compiled bytecode.
 * These are the building blocks that generated code calls via INVOKESTATIC.
 * Each method takes UDM values and returns UDM values.
 */
@Suppress("unused") // Called from generated bytecode
object RuntimeOps {

    // ── Arithmetic ──

    @JvmStatic
    fun add(left: UDM, right: UDM): UDM {
        val l = toNumber(left)
        val r = toNumber(right)
        if (l != null && r != null) return UDM.Scalar(l + r)
        // String concatenation fallback
        return UDM.Scalar(toStringValue(left) + toStringValue(right))
    }

    @JvmStatic
    fun subtract(left: UDM, right: UDM): UDM {
        return UDM.Scalar((toNumber(left) ?: 0.0) - (toNumber(right) ?: 0.0))
    }

    @JvmStatic
    fun multiply(left: UDM, right: UDM): UDM {
        return UDM.Scalar((toNumber(left) ?: 0.0) * (toNumber(right) ?: 0.0))
    }

    @JvmStatic
    fun divide(left: UDM, right: UDM): UDM {
        val r = toNumber(right) ?: 0.0
        if (r == 0.0) throw ArithmeticException("Division by zero")
        return UDM.Scalar((toNumber(left) ?: 0.0) / r)
    }

    @JvmStatic
    fun modulo(left: UDM, right: UDM): UDM {
        val r = toNumber(right) ?: 0.0
        if (r == 0.0) throw ArithmeticException("Modulo by zero")
        return UDM.Scalar((toNumber(left) ?: 0.0) % r)
    }

    // ── Comparison ──

    @JvmStatic
    fun equal(left: UDM, right: UDM): UDM {
        return UDM.Scalar(compareValues(left, right) == 0)
    }

    @JvmStatic
    fun notEqual(left: UDM, right: UDM): UDM {
        return UDM.Scalar(compareValues(left, right) != 0)
    }

    @JvmStatic
    fun greaterThan(left: UDM, right: UDM): UDM {
        return UDM.Scalar(compareValues(left, right) > 0)
    }

    @JvmStatic
    fun greaterEqual(left: UDM, right: UDM): UDM {
        return UDM.Scalar(compareValues(left, right) >= 0)
    }

    @JvmStatic
    fun lessThan(left: UDM, right: UDM): UDM {
        return UDM.Scalar(compareValues(left, right) < 0)
    }

    @JvmStatic
    fun lessEqual(left: UDM, right: UDM): UDM {
        return UDM.Scalar(compareValues(left, right) <= 0)
    }

    // ── Logical ──

    @JvmStatic
    fun isTruthy(value: UDM): Boolean {
        return when (value) {
            is UDM.Scalar -> {
                val v = value.value
                when (v) {
                    null -> false
                    is Boolean -> v
                    is Number -> v.toDouble() != 0.0
                    is String -> v.isNotEmpty()
                    else -> true
                }
            }
            is UDM.Array -> value.elements.isNotEmpty()
            is UDM.Object -> value.properties.isNotEmpty()
            else -> true
        }
    }

    @JvmStatic
    fun not(value: UDM): UDM = UDM.Scalar(!isTruthy(value))

    @JvmStatic
    fun negate(value: UDM): UDM = UDM.Scalar(-(toNumber(value) ?: 0.0))

    // ── Property access ──

    @JvmStatic
    fun getProperty(target: UDM, name: String): UDM {
        return when (target) {
            is UDM.Object -> target.properties[name] ?: UDM.Scalar.nullValue()
            else -> UDM.Scalar.nullValue()
        }
    }

    @JvmStatic
    fun getIndex(target: UDM, index: Int): UDM {
        return when (target) {
            is UDM.Array -> if (index in target.elements.indices) target.elements[index] else UDM.Scalar.nullValue()
            else -> UDM.Scalar.nullValue()
        }
    }

    // ── Null coalescing ──

    @JvmStatic
    fun nullishCoalesce(left: UDM, right: UDM): UDM {
        return if (left is UDM.Scalar && left.value == null) right else left
    }

    // ── Object/Array construction ──

    @JvmStatic
    fun buildObject(keys: Array<String>, values: Array<UDM>): UDM {
        val props = LinkedHashMap<String, UDM>(keys.size)
        for (i in keys.indices) {
            props[keys[i]] = values[i]
        }
        return UDM.Object(props)
    }

    @JvmStatic
    fun buildArray(elements: Array<UDM>): UDM {
        return UDM.Array(elements.toList())
    }

    // ── Lambda support ──

    /**
     * Invoke a UDM.Lambda with a list of arguments.
     * Used by compiled bytecode to call user-defined functions stored as local variables.
     */
    @JvmStatic
    fun invokeLambda(lambda: UDM, args: List<UDM>): UDM {
        if (lambda is UDM.Lambda) {
            return lambda.apply(args)
        }
        throw IllegalArgumentException("Expected Lambda, got ${lambda::class.simpleName}")
    }

    /**
     * Create a UDM.Lambda wrapping a static method in the generated class.
     * The method must have signature: static UDM methodName(List<UDM>)
     * Called by compiled bytecode to construct lambda values at runtime.
     */
    @JvmStatic
    fun makeLambda(clazz: Class<*>, methodName: String): UDM {
        val method = clazz.getMethod(methodName, List::class.java)
        return UDM.Lambda { args -> method.invoke(null, args) as UDM }
    }

    // ── Helpers ──

    private fun toNumber(udm: UDM): Double? {
        return when (udm) {
            is UDM.Scalar -> {
                when (val v = udm.value) {
                    is Number -> v.toDouble()
                    is String -> v.toDoubleOrNull()
                    is Boolean -> if (v) 1.0 else 0.0
                    else -> null
                }
            }
            else -> null
        }
    }

    private fun toStringValue(udm: UDM): String {
        return when (udm) {
            is UDM.Scalar -> udm.value?.toString() ?: "null"
            else -> udm.toString()
        }
    }

    private fun compareValues(left: UDM, right: UDM): Int {
        val ln = toNumber(left)
        val rn = toNumber(right)
        if (ln != null && rn != null) return ln.compareTo(rn)

        val ls = toStringValue(left)
        val rs = toStringValue(right)
        return ls.compareTo(rs)
    }
}
