package org.apache.utlx.engine.strategy.compiled

import org.apache.utlx.core.udm.UDM
import org.apache.utlx.stdlib.StandardLibrary

/**
 * Dispatches stdlib function calls from compiled bytecode.
 * Generated code calls StdlibDispatch.call(name, args) which looks up
 * the function in the StandardLibrary and invokes it.
 *
 * This avoids compiling each of the 652 stdlib functions to bytecode —
 * they're already optimized Kotlin code. The compiled bytecode just
 * needs to call them without interpreter overhead.
 */
@Suppress("unused") // Called from generated bytecode
object StdlibDispatch {

    @JvmStatic
    fun call(name: String, args: List<UDM>): UDM {
        val func = StandardLibrary.getFunction(name)
            ?: throw IllegalArgumentException("Undefined function: $name")
        return func.execute(args)
    }
}
